apiVersion: apps/v1
kind: Deployment
metadata:
  name: winn
  namespace: sopes1
spec:
  selector:
    matchLabels:
      app: winn
  template:
    metadata:
      labels:
        app: winn
    spec:
      containers:
      - name: winn
        image: cutzalluis/winn:0.5
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.1"
        env:
        - name: KAFKA_BROKER
          value: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
        - name: KAFKA_TOPIC
          value: "winners"
        - name: REDIS_HOST
          value: "redis-service"  # Servicio de Redis
        - name: REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 9090  # Cambié el puerto para evitar conflictos
---
apiVersion: v1
kind: Service
metadata:
  name: winn #DNS del servicio
  namespace: sopes1
spec:
  selector:
    app: winn
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: NodePort  # Cambia a ClusterIP si no necesitas acceso externo
