apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sopes1-ingress
  namespace: sopes1
  labels:
    name: sopes1-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: 34.28.90.174.nip.io
      http:
        paths:
          - path: /Agronomia
            pathType: Prefix
            backend:
              service:
                name: golang-client-grpc-service
                port:
                  number: 8080
          - path: /Ingenieria
            pathType: Prefix
            backend:
              service:
                name: rust-client-service
                port:
                  number: 8081
