apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: winners #concordar con el archivo ganadores.yaml
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: losers #concordar con el archivo perdedores.yaml
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
